# Generated by Django 3.2.12 on 2022-02-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bank_app.city'),
        ),
    ]
