# Generated by Django 3.2.12 on 2022-02-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_auto_20220206_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_holders',
            new_name='account_owners',
        ),
    ]
